### ISSUE TITLE
AliRoot CMake c++ check fails with binutils 2.27 if LD_LIBRARY_PATH contains /usr/lib

### ISSUE THREAD

**Issue by davidrohr** [alisw/gcc-toolchain#2]
This is reproducible on my current gentoo system with AliRoot feature-hltdev commit 23d578eb211ddbaf92c9731400cad3d77553d064, binutils 2.27, and cmake 3.7.1.

It only happens when LD_LIBRARY_PATH contains /usr/lib, I did not check in detail what library in /usr/lib breaks it.

Error message is:
  /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.4/../../../../x86_64-pc-linux-gnu/bin/ld:
  symbol lookup error:
  /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.4/../../../../x86_64-pc-linux-gnu/bin/ld:
  undefined symbol: rx_additional_link_map_text

during
CMake Error at /usr/share/cmake/Modules/CMakeTestCXXCompiler.cmake:44 (message):
  The C++ compiler "/usr/bin/c++" is not able to compile a simple test
  program.

**Comment by ktf** [comment]
Ciao,

this is due to the fact it mixes system and our environment, which probably on Gentoo are not compatible. Can you attach the output of aliDoctor?

--
Ciao,
Giulio

**Comment by davidrohr** [comment]
Ciao Giulio,
we do not use AliBuild in the HLT, and I fixed the issue for us already by changing the LD_LIBRARY_PATH. After talking to Dario, I created this entry as reference, in case you see similar issues when moving to binutils 2.27.

**Comment by ktf** [comment]
Ah, ok, sorry for the noise.
